### ISSUE TITLE
checking author affiliation and country name capitalization

### ISSUE THREAD

**Issue by asiddiqi14** [GaretJax/irco#11]
in some cases the raw data has country name in capital letters, could this be interfering in associating author affiliations to country names? I am sending a detailed file and some raw data for you to please check.

**Comment by GaretJax** [comment]
I fixed some stuff in the parsing module. None of that was due to capitalization.
There decisions I need in order to continue the work:

Considering that records have the following relevant fields:
- Authors (`AF`)
- Affiliations (`C1`)
- Reprint author with affiliation (`RP`)

## Decision 1:

The `affiliations` field normally contains a mapping between authors and their affiliation. If that's the case everything is simple, but sometimes it just contains a list of institutions. In this case, we have three different cases:
1. The number of authors equals the number of institutions ==> I can map each author to the institution at the same position in the list.
2. There is just one institution and multiple authors ==> Each author is affiliated with the same institution.
3. There is more than one institution and more than one author, and their count differs. ==> How to map authors to institutions in this case? (see `savedrecs-7.txt:859`, `savedrecs-7.txt:869`, `savedrecs-7.txt:873` and `savedrecs-7.txt:887` for some examples).

## Decision 2

Almost always, a reprint author affiliation is provided in the `affiliations` field as well as in the `reprint author` field. In most cases these two affiliations are the same, but in some cases they differ. Which one should be assigned to the author in this case? (Note that the chosen one will become its unique affiliation).

**Comment by asiddiqi14** [comment]
I think for Decision 2, we should use the information provided in the reprint author field.  So if the affiliation differs in the 'affiliations' field and in the 'reprint author' field, let's have the 'reprint author' field be dominant and assign that unique affiliation information to the reprint author. 

For decision 1, I think the issue is that some times authors have multiple affiliations. One author can have two more affiliations at the same time and they list all of those out in their papers. That is why there are cases where there are more affiliations than authors. The question of how to assign them to individuals is tricky - and would amount to guessing. In the interest of rigor, let us leave those records out from the analysis for now and simply generate a report that shows how many such records were left out.

**Comment by GaretJax** [comment]
These changes are incorporated in 0.9
